debian/tmp/usr/sbin/rpc.lockd sbin/
debian/tmp/usr/sbin/rpc.statd sbin/
debian/tmp/usr/sbin/showmount sbin/
debian/tmp/usr/sbin/nfsstat
debian/tmp/usr/sbin/rpc.gssd
debian/tmp/usr/sbin/rpc.idmapd
debian/idmapd.conf usr/share/nfs-common/conffiles/
debian/idmapd.conf.md5sum usr/share/nfs-common/conffiles/
debian/nfs-common.default usr/share/nfs-common/conffiles/
debian/nfs-common.default.md5sum usr/share/nfs-common/conffiles/
