#!/bin/sh

set -e

case "$1" in
    configure)
        ucf --three-way /usr/share/nfs-common/conffiles/idmapd.conf /etc/idmapd.conf
        ucf --three-way /usr/share/nfs-common/conffiles/nfs-common.default /etc/default/nfs-common
        ucf --three-way /usr/share/nfs-common/conffiles/nfs.conf /etc/nfs.conf

        if ! getent passwd statd >/dev/null; then
            adduser --system --home /var/lib/nfs --no-create-home statd
        fi

        # Don't make /var/lib/nfs owned by statd. Only sm and sm.bak need to be
        # accessible by statd or sm-notify after they drop privileges.
        # https://bugs.debian.org/940848 (CVE-2019-3689)
        if dpkg --compare-versions "$2" lt 1:1.3.4-3; then
                chown root:root /var/lib/nfs
        fi
        chown statd: /var/lib/nfs/sm \
            /var/lib/nfs/sm.bak
        if [ -f /var/lib/nfs/state ]; then
            chown statd /var/lib/nfs/state
        fi
    ;;
esac

#DEBHELPER#
