debian/tmp/usr/sbin/exportfs
debian/tmp/sbin/nfsdcltrack
debian/tmp/usr/sbin/fsidd
debian/tmp/usr/sbin/nfsdcld
debian/tmp/usr/sbin/nfsdclddb
debian/tmp/usr/sbin/nfsdclnts
debian/tmp/usr/sbin/rpc.mountd
debian/tmp/usr/sbin/rpc.nfsd
debian/tmp/var/lib/nfs/etab
debian/tmp/var/lib/nfs/rmtab
debian/nfs-kernel-server.default /usr/share/nfs-kernel-server/conffiles/
debian/etc.exports /usr/share/nfs-kernel-server/conffiles/
debian/tmp/lib/systemd/system/fsidd.service
debian/tmp/lib/systemd/system/nfs-blkmap.service
debian/tmp/lib/systemd/system/nfs-mountd.service
debian/tmp/lib/systemd/system/nfs-server.service
debian/tmp/lib/systemd/system/nfsdcld.service
debian/tmp/lib/systemd/system-generators/nfs-server-generator
debian/tmp/usr/lib/udev/rules.d/60-nfs.rules
