#!/bin/sh -e

#DEBHELPER#

case "$1" in
    configure)
	update-rc.d nfs-common defaults 21 79 >/dev/null

	if ! getent passwd statd >/dev/null; then
	    adduser --system --home /var/lib/nfs --no-create-home statd
	fi
	if [ "$2" = "" ] || dpkg --compare-versions "$2" lt 1.0.7-10; then
	    chown statd /var/lib/nfs/sm \
		/var/lib/nfs/sm.bak \
		/var/lib/nfs/state \
		/var/lib/nfs/rpc_pipefs
	fi
    ;;
esac

act="restart"
[ "$1:$2" = "configure:" ] && act="start"
invoke-rc.d nfs-common $act
